---
format: gfm
engine: knitr
---

# Quarto Live modification of the [Posit Programming Basics primer](https://github.com/rstudio-education/primers/blob/master/basics/04-Programming-Basics/04-Programming-Basics.Rmd)

`r emoji::emoji("rocket")` [Launch Tutorial](https://mdlama.github.io/Programming_Basics/) 

## Course Description

R is easiest to use when you know how the R language works. This tutorial will teach you the implicit background knowledge that informs every piece of R code.

In this tutorial, you'll learn about:

* **functions** and their **arguments**
* **objects**
* R's basic **data types** 
* R's basic data structures including **vectors** and **lists**
* R's **package system**

### Built with

[Quarto Live](https://r-wasm.github.io/quarto-live/) - WebAssembly powered code blocks and exercises for Quarto HTML documents. Quarto is the "next generation" of [R Markdown](http://rmarkdown.rstudio.com/). Quarto Live uses [WebR](https://docs.r-wasm.org/webr/latest/), which facilitates running R code directly in the browser with no need for a server.

## Acknowledgments

R for Data Science from O'Reilly Media, Inc. Copyright © 2017 Garrett Grolemund, Hadley Wickham. Used with permission.

### License

This work is licensed under the Creative Commons
Attribution-ShareAlike 4.0 License (CC BY-SA 4.0) - see the [LICENSE](LICENSE.md) file for details.
